line-length = 120
target-version = "py312"

fix = true
extend-exclude = []

[lint]
select = [
    "ALL",
]

        
[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"